categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version 0.6.1 of deFuse
long_description: |
  deFuse - gene fusion discovery using RNA-Seq data

  deFuse is a software package for gene fusion discovery using RNA-Seq data. 
  The software uses clusters of discordant paired end alignments 
  to inform a split read alignment analysis for finding fusion boundaries.  
  The software also employs a number of heuristic filters in an attempt 
  to reduce the number of false positives and produces 
  a fully annotated output for each predicted fusion.

  http://sourceforge.net/apps/mediawiki/defuse/

name: package_defuse_0_6_1
owner: jjohnson
remote_repository_url: https://github.com/jj-umn/galaxytools/tree/master/packages/package_defuse_0_6_1
type: tool_dependency_definition
