owner: jjohnson
name: package_optitype_0_1
categories:
- Tool Dependency Packages
description: Installs OptiType v1.0 in a python virtual environment
long_description: |
  OptiType - Precision HLA typing from next-generation sequencing data 

  https://github.com/FRED-2/OptiType
remote_repository_url: https://github.com/jj-umn/galaxytools/tree/master/packages/package_optitype_0_1
type: tool_dependency_definition
